### PR TITLE
REF: Move no_device_lazy_load from lucid to typhos.

### PR DESCRIPTION
**Pull request by hhslepicka**
Depends on https://github.com/pcdshub/typhos/pull/241

### CODE REVIEW

**Comment by hhslepicka** [comment]
Now this should work and not take forever to open due to every signal timeout on connection:
```python
from qtpy.QtWidgets import QApplication
import typhos
app = QApplication([])
import pcdsdevices.spectrometer
with typhos.utils.no_device_lazy_load():
    mono = pcdsdevices.spectrometer.Kmono('PREFIX:', name='mono')
    display = typhos.TyphosSuite.from_device(mono)
display.show()
```

**Comment by klauer** [comment]
Are tests passing locally? They won't on travis due to the dependency on an unreleased typhos version.

**Comment by klauer** [comment]
@hhslepicka reports in person that tests + flake8 are passing.

**Comment by klauer** [comment]
@hhslepicka reports in person that tests + flake8 are passing.

**Comment by hhslepicka** [comment]
I am @hhslepicka and I approve this message.

**Comment by hhslepicka** [comment]
I am @hhslepicka and I approve this message.

**Pull request merged**
