### PR TITLE
CI: test python 3.8 as well

### PR DESCRIPTION
**Pull request by klauer**

### CODE REVIEW

**Comment by klauer** [comment]
Conda says 🚫 🎲 no dice😦

**Comment by klauer** [comment]
Failing at least in part because pyqtads is not on Python 3.8.

**Comment by hhslepicka** [comment]
I am checking with the conda-forge team how to enable 3.8 and I will make a PR for pyqtads to add that.

**Comment by hhslepicka** [comment]
Bumping CI now that pyqtads is available for 3.8

**Comment by hhslepicka** [comment]
The flake8 linting failure here makes no sense... I checked out the code and locally flake8 with the same version as CI is not resulting in error.
Also, the import of Happi is used at launcher.py:108.

**Pull request merged**
